FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci 

# Copy the rest of the source code (including .env files)
COPY . .

# Build the app - it will automatically use the appropriate the environment variables
# from the env_file build in docker-compose

# Build the app
RUN npm run build

# ---------- Production stage ----------
FROM nginx:stable-alpine

# Copy built frontend files from builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy nginx config AND RENAME to .conf extension
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]