#------build stage-------
FROM node:20-alpine AS builder

#set working directory
WORKDIR /app

#install dependencies
COPY package*.json ./
RUN npm install

#Copy the rest of the source code
COPY . .

#Build the app
RUN npm run build

#----------Production stage----------
FROM nginx:stable-alpine

#Copy built frontend files from bilder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy a default nginx config 
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

#Start Nginx
CMD [ "nginx", "-g", "daemon off;" ]