@startuml
skinparam linetype ortho
entity "User" as User {
    email : string <<PK>>
    --
    first_name : string
    last_name : string
    password : string
}

entity "Customer" as Customer {
    + email : int <<PK, FK>>
    --
    address : address_id <<FK>>
}

entity "Artist" as Artist {
    + email : int <<PK, FK>>
    --
    bio : string
    style : string
}

entity "Product" as Product {
    + product_id : int <<PK>>
    --
    title : string
    price : decimal
    currency : string
    email : int <<FK>>
}

entity "Order" as Order {
    + order_id : int <<PK>>
    --
    order_date : date
    order_status : string
    email : int <<FK>>
}

entity "OrderDetail" as OrderDetail {
    + order_detail_id : int <<PK>>
    --
    order_id : int <<FK>>
    product_id : int <<FK>>
    quantity : int
}

entity "Address" as Address {
    + address_id : int <<PK>>
    --
    customer_id : int <<FK>>
    street : string
    city : string
    postal_code : string
    country : string
}

' -------------------
' RELATIONSHIPS
' -------------------
User ||--|| Customer : "is"
User ||--|| Artist : "is"
Customer ||--o{ Order : "places"
Order ||--o{ OrderDetail : "contains"
Product ||--o{ OrderDetail : "included in"
Artist ||--o{ Product : "sells"
Customer ||-up-o{ Address : "has"

@enduml
