@startuml
skinparam linetype ortho
entity "User" as User {
    id : string <<PK>>
    --
    first_name : string
    last_name : string
    email : string
    password : string
}

entity "Artist" as Artist {
    + user-id : int <<PK, FK>>
    --
    bio : string
    style : string
}

entity "Product" as Product {
    + id : int <<PK>>
    --
    title : string
    secret_price : decimal
    currency : string
    image_url : string
    quantity : int
    artist_id : int <<FK>>
}

entity "Order" as Order {
    + id : int <<PK>>
    --
    order_date : date
    order_status : string
    customer_id : int <<FK>>
    product_id : int <<FK>>
    address_id : int <<FK>>
    total_price : decimal
}

entity "Address" as Address {
    + id : int <<PK>>
    --
    street : string
    city : string
    postal_code : string
    country : string
    user_id : string <<FK>>
}

' -------------------
' RELATIONSHIPS
' -------------------
User }o--o{ Order : "has"
Artist ||-right-|| User : "is"
Order }o--o{ Product : "contains"
Artist ||-down-o{ Product : "creates"
User ||-right-o{ Address : "has"

@enduml
