name: Fullstack App CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------
      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      # -------------------------------
      # Clean install to fix Rollup optional dependency bug
      - name: Clean npm install (to fix rullup bug)
        run: | 
          rm -rf node-moudles package-lock-json
          npm cache clean --force
          npm install
        working-directory: ./frontend
        
      # -------------------------------
      # 3. Install frontend dependencies
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      # -------------------------------
      # 4. TypeScript check
      - name: TypeScript check
        run: npm run type-checking
        working-directory: ./frontend

      # -------------------------------
      # 5. Run frontend tests
      - name: Run frontend tests
        run: npm test -- --watch=false
        working-directory: ./frontend

      # -------------------------------
      # 6. Build frontend
      - name: Build frontend project
        run: npm run build
        working-directory: ./frontend

      - name: List dist folder
        run: ls -la ./frontend/dist

      # -------------------------------
      # 7. (Optional) Docker steps
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-frontend:latest ./frontend

      - name: Push frontend Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-frontend:latest

      # -------------------------------
      # 8. Install Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # -------------------------------
      # 9. Deploy to Netlify
      - name: Deploy to Netlify
        run: netlify deploy --dir=./frontend/dist --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
